version: "3"

services:
  web:
    build: . # build from Dockerfile
    entrypoint: /entrypoint.sh
    command: python manage.py runserver 0.0.0.0:8001
    #  maps ports and container code/database to local filesystem
    ports:
      - "8001:8001"
    volumes:
      - .:/usr/src/app_djdocker_blog
